name: ci

on:
  push:
    branches:
    - main  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: exam-rncp 
      COMMIT: ${{ github.sha }}
      REPO: carts
    steps:
    - uses: actions/checkout@v4


    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'semeru'
        java-version: 8

